package model;

import model.base.BaseArticles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Articles extends BaseArticles<Articles> {
	public static final Articles dao = new Articles().dao();
}
