package model;

import model.base.BaseArticleComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleComments extends BaseArticleComments<ArticleComments> {
	public static final ArticleComments dao = new ArticleComments().dao();
}
