package model;

import model.base.BaseBuyersShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyersShow extends BaseBuyersShow<BuyersShow> {
	public static final BuyersShow dao = new BuyersShow().dao();
}
