package model;

import model.base.BaseCarriers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carriers extends BaseCarriers<Carriers> {
	public static final Carriers dao = new Carriers().dao();
}
