package model;

import model.base.BaseCarts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carts extends BaseCarts<Carts> {
	public static final Carts dao = new Carts().dao();
}
