package model;

import model.base.BaseClassifications;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classifications extends BaseClassifications<Classifications> {
	public static final Classifications dao = new Classifications().dao();
}
