package model;

import model.base.BaseCollects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collects extends BaseCollects<Collects> {
	public static final Collects dao = new Collects().dao();
}
