package model;

import model.base.BaseCountriesProvinces;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CountriesProvinces extends BaseCountriesProvinces<CountriesProvinces> {
	public static final CountriesProvinces dao = new CountriesProvinces().dao();
}
