package model;

import model.base.BaseFriends;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Friends extends BaseFriends<Friends> {
	public static final Friends dao = new Friends().dao();
}
