package model;

import model.base.BaseHotNav;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotNav extends BaseHotNav<HotNav> {
	public static final HotNav dao = new HotNav().dao();
}
