package model;

import model.base.BaseInvitationCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvitationCode extends BaseInvitationCode<InvitationCode> {
	public static final InvitationCode dao = new InvitationCode().dao();
}
