package model;

import model.base.BaseMessages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Messages extends BaseMessages<Messages> {
	public static final Messages dao = new Messages().dao();
}
