package model;

import model.base.BaseNotices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notices extends BaseNotices<Notices> {
	public static final Notices dao = new Notices().dao();
}
