package model;

import model.base.BaseOrdersItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersItem extends BaseOrdersItem<OrdersItem> {
	public static final OrdersItem dao = new OrdersItem().dao();
}
