package model;

import model.base.BaseOrderDelivery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDelivery extends BaseOrderDelivery<OrderDelivery> {
	public static final OrderDelivery dao = new OrderDelivery().dao();
}
