package model;

import model.base.BaseOrderLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLogs extends BaseOrderLogs<OrderLogs> {
	public static final OrderLogs dao = new OrderLogs().dao();
}
