package model;

import model.base.BaseOrderVerify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderVerify extends BaseOrderVerify<OrderVerify> {
	public static final OrderVerify dao = new OrderVerify().dao();
}
