package model;

import model.base.BasePayLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayLogs extends BasePayLogs<PayLogs> {
	public static final PayLogs dao = new PayLogs().dao();
}
