package model;

import model.base.BaseProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Products extends BaseProducts<Products> {
	public static final Products dao = new Products().dao();
}
