package model;

import model.base.BaseProductShippingPolicy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductShippingPolicy extends BaseProductShippingPolicy<ProductShippingPolicy> {
	public static final ProductShippingPolicy dao = new ProductShippingPolicy().dao();
}
