package model;

import model.base.BaseProductsAttrs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductsAttrs extends BaseProductsAttrs<ProductsAttrs> {
	public static final ProductsAttrs dao = new ProductsAttrs().dao();
}
