package model;

import model.base.BaseProductsWxapp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductsWxapp extends BaseProductsWxapp<ProductsWxapp> {
	public static final ProductsWxapp dao = new ProductsWxapp().dao();
}
