package model;

import model.base.BaseRefundApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RefundApply extends BaseRefundApply<RefundApply> {
	public static final RefundApply dao = new RefundApply().dao();
}
