package model;

import model.base.BaseSellerSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SellerSetting extends BaseSellerSetting<SellerSetting> {
	public static final SellerSetting dao = new SellerSetting().dao();
}
