package model;

import model.base.BaseSellAttrs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SellAttrs extends BaseSellAttrs<SellAttrs> {
	public static final SellAttrs dao = new SellAttrs().dao();
}
