package model;

import model.base.BaseShippingTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingTemplate extends BaseShippingTemplate<ShippingTemplate> {
	public static final ShippingTemplate dao = new ShippingTemplate().dao();
}
