package model;

import model.base.BaseSpecialWxapp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialWxapp extends BaseSpecialWxapp<SpecialWxapp> {
	public static final SpecialWxapp dao = new SpecialWxapp().dao();
}
