package model;

import model.base.BaseSpecialProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialProducts extends BaseSpecialProducts<SpecialProducts> {
	public static final SpecialProducts dao = new SpecialProducts().dao();
}
