package model;

import model.base.BaseUserClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserClient extends BaseUserClient<UserClient> {
	public static final UserClient dao = new UserClient().dao();
}
