package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends Model<M> implements IBean {

	public M setAddressId(java.lang.Integer addressId) {
		set("address_id", addressId);
		return (M)this;
	}

	public java.lang.Integer getAddressId() {
		return get("address_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setAddressName(java.lang.String addressName) {
		set("address_name", addressName);
		return (M)this;
	}

	public java.lang.String getAddressName() {
		return get("address_name");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public M setCountryCode(java.lang.Integer countryCode) {
		set("country_code", countryCode);
		return (M)this;
	}

	public java.lang.Integer getCountryCode() {
		return get("country_code");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public M setProvinceCode(java.lang.Integer provinceCode) {
		set("province_code", provinceCode);
		return (M)this;
	}

	public java.lang.Integer getProvinceCode() {
		return get("province_code");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCityCode(java.lang.Integer cityCode) {
		set("city_code", cityCode);
		return (M)this;
	}

	public java.lang.Integer getCityCode() {
		return get("city_code");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setDistrictCode(java.lang.Integer districtCode) {
		set("district_code", districtCode);
		return (M)this;
	}

	public java.lang.Integer getDistrictCode() {
		return get("district_code");
	}

	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
		return (M)this;
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}

	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
