package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrdersItem<M extends BaseOrdersItem<M>> extends Model<M> implements IBean {

	public M setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
		return (M)this;
	}

	public java.lang.Integer getItemId() {
		return get("item_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setSkuId(java.lang.Integer skuId) {
		set("sku_id", skuId);
		return (M)this;
	}

	public java.lang.Integer getSkuId() {
		return get("sku_id");
	}

	public M setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
		return (M)this;
	}

	public java.lang.Integer getTemplateId() {
		return get("template_id");
	}

	public M setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
		return (M)this;
	}

	public java.lang.String getTemplateName() {
		return get("template_name");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public M setProductImg(java.lang.String productImg) {
		set("product_img", productImg);
		return (M)this;
	}

	public java.lang.String getProductImg() {
		return get("product_img");
	}

	public M setProductPrice(java.math.BigDecimal productPrice) {
		set("product_price", productPrice);
		return (M)this;
	}

	public java.math.BigDecimal getProductPrice() {
		return get("product_price");
	}

	public M setProductNum(java.lang.Integer productNum) {
		set("product_num", productNum);
		return (M)this;
	}

	public java.lang.Integer getProductNum() {
		return get("product_num");
	}

	public M setSkuColor(java.lang.String skuColor) {
		set("sku_color", skuColor);
		return (M)this;
	}

	public java.lang.String getSkuColor() {
		return get("sku_color");
	}

	public M setSkuSize(java.lang.String skuSize) {
		set("sku_size", skuSize);
		return (M)this;
	}

	public java.lang.String getSkuSize() {
		return get("sku_size");
	}

}
