package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserClient<M extends BaseUserClient<M>> extends Model<M> implements IBean {

	public M setClientId(java.lang.Integer clientId) {
		set("client_id", clientId);
		return (M)this;
	}

	public java.lang.Integer getClientId() {
		return get("client_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setDeviceToken(java.lang.String deviceToken) {
		set("device_token", deviceToken);
		return (M)this;
	}

	public java.lang.String getDeviceToken() {
		return get("device_token");
	}

	public M setClientVersion(java.lang.String clientVersion) {
		set("client_version", clientVersion);
		return (M)this;
	}

	public java.lang.String getClientVersion() {
		return get("client_version");
	}

	public M setChannel(java.lang.String channel) {
		set("channel", channel);
		return (M)this;
	}

	public java.lang.String getChannel() {
		return get("channel");
	}

	public M setPhoneModel(java.lang.String phoneModel) {
		set("phone_model", phoneModel);
		return (M)this;
	}

	public java.lang.String getPhoneModel() {
		return get("phone_model");
	}

	public M setClientPlatform(java.lang.Integer clientPlatform) {
		set("client_platform", clientPlatform);
		return (M)this;
	}

	public java.lang.Integer getClientPlatform() {
		return get("client_platform");
	}

	public M setSystemVersion(java.lang.String systemVersion) {
		set("system_version", systemVersion);
		return (M)this;
	}

	public java.lang.String getSystemVersion() {
		return get("system_version");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

}
