package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderVerify<M extends BaseOrderVerify<M>> extends Model<M> implements IBean {

	public M setVerifyId(java.lang.Integer verifyId) {
		set("verify_id", verifyId);
		return (M)this;
	}

	public java.lang.Integer getVerifyId() {
		return get("verify_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setPhotoAngle(java.lang.Integer photoAngle) {
		set("photo_angle", photoAngle);
		return (M)this;
	}

	public java.lang.Integer getPhotoAngle() {
		return get("photo_angle");
	}

	public M setAngleName(java.lang.String angleName) {
		set("angle_name", angleName);
		return (M)this;
	}

	public java.lang.String getAngleName() {
		return get("angle_name");
	}

	public M setPhotoUrls(java.lang.String photoUrls) {
		set("photo_urls", photoUrls);
		return (M)this;
	}

	public java.lang.String getPhotoUrls() {
		return get("photo_urls");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
