package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellAttrs<M extends BaseSellAttrs<M>> extends Model<M> implements IBean {

	public M setSkuId(java.lang.Integer skuId) {
		set("sku_id", skuId);
		return (M)this;
	}

	public java.lang.Integer getSkuId() {
		return get("sku_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setSkuImg(java.lang.String skuImg) {
		set("sku_img", skuImg);
		return (M)this;
	}

	public java.lang.String getSkuImg() {
		return get("sku_img");
	}

	public M setSkuColor(java.lang.String skuColor) {
		set("sku_color", skuColor);
		return (M)this;
	}

	public java.lang.String getSkuColor() {
		return get("sku_color");
	}

	public M setSkuSize(java.lang.String skuSize) {
		set("sku_size", skuSize);
		return (M)this;
	}

	public java.lang.String getSkuSize() {
		return get("sku_size");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setInitialPrice(java.math.BigDecimal initialPrice) {
		set("initial_price", initialPrice);
		return (M)this;
	}

	public java.math.BigDecimal getInitialPrice() {
		return get("initial_price");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public M setSellStatus(java.lang.Integer sellStatus) {
		set("sell_status", sellStatus);
		return (M)this;
	}

	public java.lang.Integer getSellStatus() {
		return get("sell_status");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
