package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSpecialProducts<M extends BaseSpecialProducts<M>> extends Model<M> implements IBean {

	public M setPkid(java.lang.Integer pkid) {
		set("pkid", pkid);
		return (M)this;
	}

	public java.lang.Integer getPkid() {
		return get("pkid");
	}

	public M setSpecialId(java.lang.Integer specialId) {
		set("special_id", specialId);
		return (M)this;
	}

	public java.lang.Integer getSpecialId() {
		return get("special_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

}
