package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductsWxapp<M extends BaseProductsWxapp<M>> extends Model<M> implements IBean {

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setCounterPriceCurrency(java.lang.Integer counterPriceCurrency) {
		set("counter_price_currency", counterPriceCurrency);
		return (M)this;
	}

	public java.lang.Integer getCounterPriceCurrency() {
		return get("counter_price_currency");
	}

	public M setCounterPrice(java.math.BigDecimal counterPrice) {
		set("counter_price", counterPrice);
		return (M)this;
	}

	public java.math.BigDecimal getCounterPrice() {
		return get("counter_price");
	}

	public M setPurchasePriceCurrency(java.lang.Integer purchasePriceCurrency) {
		set("purchase_price_currency", purchasePriceCurrency);
		return (M)this;
	}

	public java.lang.Integer getPurchasePriceCurrency() {
		return get("purchase_price_currency");
	}

	public M setPurchasePrice(java.math.BigDecimal purchasePrice) {
		set("purchase_price", purchasePrice);
		return (M)this;
	}

	public java.math.BigDecimal getPurchasePrice() {
		return get("purchase_price");
	}

	public M setOtherPriceCurrency(java.lang.Integer otherPriceCurrency) {
		set("other_price_currency", otherPriceCurrency);
		return (M)this;
	}

	public java.lang.Integer getOtherPriceCurrency() {
		return get("other_price_currency");
	}

	public M setOtherPrice(java.math.BigDecimal otherPrice) {
		set("other_price", otherPrice);
		return (M)this;
	}

	public java.math.BigDecimal getOtherPrice() {
		return get("other_price");
	}

}
