package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public M setUserAvatar(java.lang.String userAvatar) {
		set("user_avatar", userAvatar);
		return (M)this;
	}

	public java.lang.String getUserAvatar() {
		return get("user_avatar");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setPlatformType(java.lang.Integer platformType) {
		set("platform_type", platformType);
		return (M)this;
	}

	public java.lang.Integer getPlatformType() {
		return get("platform_type");
	}

	public M setPlatformId(java.lang.String platformId) {
		set("platform_id", platformId);
		return (M)this;
	}

	public java.lang.String getPlatformId() {
		return get("platform_id");
	}

	public M setIsSellers(java.lang.Boolean isSellers) {
		set("is_sellers", isSellers);
		return (M)this;
	}

	public java.lang.Boolean getIsSellers() {
		return get("is_sellers");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public M setCountry(java.lang.Integer country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.Integer getCountry() {
		return get("country");
	}

	public M setProvince(java.lang.Integer province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.Integer getProvince() {
		return get("province");
	}

	public M setCity(java.lang.Integer city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.Integer getCity() {
		return get("city");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setImOken(java.lang.String imOken) {
		set("im_oken", imOken);
		return (M)this;
	}

	public java.lang.String getImOken() {
		return get("im_oken");
	}

	public M setExtend(java.lang.String extend) {
		set("extend", extend);
		return (M)this;
	}

	public java.lang.String getExtend() {
		return get("extend");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public M setWxAccount(java.lang.String wxAccount) {
		set("wx_account", wxAccount);
		return (M)this;
	}

	public java.lang.String getWxAccount() {
		return get("wx_account");
	}

}
