package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCollects<M extends BaseCollects<M>> extends Model<M> implements IBean {

	public M setCollectId(java.lang.Integer collectId) {
		set("collect_id", collectId);
		return (M)this;
	}

	public java.lang.Integer getCollectId() {
		return get("collect_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setArticleId(java.lang.Integer articleId) {
		set("article_id", articleId);
		return (M)this;
	}

	public java.lang.Integer getArticleId() {
		return get("article_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setSystemType(java.lang.Integer systemType) {
		set("system_type", systemType);
		return (M)this;
	}

	public java.lang.Integer getSystemType() {
		return get("system_type");
	}

}
