package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClassifications<M extends BaseClassifications<M>> extends Model<M> implements IBean {

	public M setClassificationId(java.lang.Integer classificationId) {
		set("classification_id", classificationId);
		return (M)this;
	}

	public java.lang.Integer getClassificationId() {
		return get("classification_id");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public M setClassificationName(java.lang.String classificationName) {
		set("classification_name", classificationName);
		return (M)this;
	}

	public java.lang.String getClassificationName() {
		return get("classification_name");
	}

	public M setClassificationSort(java.lang.Integer classificationSort) {
		set("classification_sort", classificationSort);
		return (M)this;
	}

	public java.lang.Integer getClassificationSort() {
		return get("classification_sort");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
