package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCountriesProvinces<M extends BaseCountriesProvinces<M>> extends Model<M> implements IBean {

	public M setCountriesId(java.lang.Long countriesId) {
		set("countries_id", countriesId);
		return (M)this;
	}

	public java.lang.Long getCountriesId() {
		return get("countries_id");
	}

	public M setCountriesName(java.lang.String countriesName) {
		set("countries_name", countriesName);
		return (M)this;
	}

	public java.lang.String getCountriesName() {
		return get("countries_name");
	}

	public M setCountriesCode(java.lang.String countriesCode) {
		set("countries_code", countriesCode);
		return (M)this;
	}

	public java.lang.String getCountriesCode() {
		return get("countries_code");
	}

	public M setCountriesParentCode(java.lang.String countriesParentCode) {
		set("countries_parent_code", countriesParentCode);
		return (M)this;
	}

	public java.lang.String getCountriesParentCode() {
		return get("countries_parent_code");
	}

	public M setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
