package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerSetting<M extends BaseSellerSetting<M>> extends Model<M> implements IBean {

	public M setSettingId(java.lang.Integer settingId) {
		set("setting_id", settingId);
		return (M)this;
	}

	public java.lang.Integer getSettingId() {
		return get("setting_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setEurExchangeRate(java.math.BigDecimal eurExchangeRate) {
		set("eur_exchange_rate", eurExchangeRate);
		return (M)this;
	}

	public java.math.BigDecimal getEurExchangeRate() {
		return get("eur_exchange_rate");
	}

	public M setGbpExchangeRate(java.math.BigDecimal gbpExchangeRate) {
		set("gbp_exchange_rate", gbpExchangeRate);
		return (M)this;
	}

	public java.math.BigDecimal getGbpExchangeRate() {
		return get("gbp_exchange_rate");
	}

	public M setNotice(java.lang.String notice) {
		set("notice", notice);
		return (M)this;
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public M setShopImg(java.lang.String shopImg) {
		set("shop_img", shopImg);
		return (M)this;
	}

	public java.lang.String getShopImg() {
		return get("shop_img");
	}

	public M setToutiao(java.lang.String toutiao) {
		set("toutiao", toutiao);
		return (M)this;
	}

	public java.lang.String getToutiao() {
		return get("toutiao");
	}

	public M setToutiaoImg(java.lang.String toutiaoImg) {
		set("toutiao_img", toutiaoImg);
		return (M)this;
	}

	public java.lang.String getToutiaoImg() {
		return get("toutiao_img");
	}

}
