package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductsAttrs<M extends BaseProductsAttrs<M>> extends Model<M> implements IBean {

	public M setAttrId(java.lang.Integer attrId) {
		set("attr_id", attrId);
		return (M)this;
	}

	public java.lang.Integer getAttrId() {
		return get("attr_id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setAttrName(java.lang.String attrName) {
		set("attr_name", attrName);
		return (M)this;
	}

	public java.lang.String getAttrName() {
		return get("attr_name");
	}

	public M setAttrValue(java.lang.String attrValue) {
		set("attr_value", attrValue);
		return (M)this;
	}

	public java.lang.String getAttrValue() {
		return get("attr_value");
	}

}
