package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvitationCode<M extends BaseInvitationCode<M>> extends Model<M> implements IBean {

	public M setCodeId(java.lang.Integer codeId) {
		set("code_id", codeId);
		return (M)this;
	}

	public java.lang.Integer getCodeId() {
		return get("code_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setIsUsed(java.lang.Boolean isUsed) {
		set("is_used", isUsed);
		return (M)this;
	}

	public java.lang.Boolean getIsUsed() {
		return get("is_used");
	}

	public M setUseUserId(java.lang.Integer useUserId) {
		set("use_user_id", useUserId);
		return (M)this;
	}

	public java.lang.Integer getUseUserId() {
		return get("use_user_id");
	}

	public M setUseNickname(java.lang.String useNickname) {
		set("use_nickname", useNickname);
		return (M)this;
	}

	public java.lang.String getUseNickname() {
		return get("use_nickname");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUsetime(java.util.Date usetime) {
		set("usetime", usetime);
		return (M)this;
	}

	public java.util.Date getUsetime() {
		return get("usetime");
	}

}
