package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNotices<M extends BaseNotices<M>> extends Model<M> implements IBean {

	public M setNoticeId(java.lang.Long noticeId) {
		set("notice_id", noticeId);
		return (M)this;
	}

	public java.lang.Long getNoticeId() {
		return get("notice_id");
	}

	public M setNoticeTitle(java.lang.String noticeTitle) {
		set("notice_title", noticeTitle);
		return (M)this;
	}

	public java.lang.String getNoticeTitle() {
		return get("notice_title");
	}

	public M setNoticeContent(java.lang.String noticeContent) {
		set("notice_content", noticeContent);
		return (M)this;
	}

	public java.lang.String getNoticeContent() {
		return get("notice_content");
	}

	public M setNoticeImg(java.lang.String noticeImg) {
		set("notice_img", noticeImg);
		return (M)this;
	}

	public java.lang.String getNoticeImg() {
		return get("notice_img");
	}

	public M setNoticeType(java.lang.Integer noticeType) {
		set("notice_type", noticeType);
		return (M)this;
	}

	public java.lang.Integer getNoticeType() {
		return get("notice_type");
	}

	public M setNoticeCommonId(java.lang.Long noticeCommonId) {
		set("notice_common_id", noticeCommonId);
		return (M)this;
	}

	public java.lang.Long getNoticeCommonId() {
		return get("notice_common_id");
	}

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
