package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticles<M extends BaseArticles<M>> extends Model<M> implements IBean {

	public M setArticleId(java.lang.Integer articleId) {
		set("article_id", articleId);
		return (M)this;
	}

	public java.lang.Integer getArticleId() {
		return get("article_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setArticleType(java.lang.Integer articleType) {
		set("article_type", articleType);
		return (M)this;
	}

	public java.lang.Integer getArticleType() {
		return get("article_type");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setRelatedProducts(java.lang.String relatedProducts) {
		set("related_products", relatedProducts);
		return (M)this;
	}

	public java.lang.String getRelatedProducts() {
		return get("related_products");
	}

	public M setPageviews(java.lang.Integer pageviews) {
		set("pageviews", pageviews);
		return (M)this;
	}

	public java.lang.Integer getPageviews() {
		return get("pageviews");
	}

	public M setCommentsAmount(java.lang.Integer commentsAmount) {
		set("comments_amount", commentsAmount);
		return (M)this;
	}

	public java.lang.Integer getCommentsAmount() {
		return get("comments_amount");
	}

	public M setLikeAmount(java.lang.Integer likeAmount) {
		set("like_amount", likeAmount);
		return (M)this;
	}

	public java.lang.Integer getLikeAmount() {
		return get("like_amount");
	}

	public M setCollectsAnount(java.lang.Integer collectsAnount) {
		set("collects_anount", collectsAnount);
		return (M)this;
	}

	public java.lang.Integer getCollectsAnount() {
		return get("collects_anount");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
