package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRefundApply<M extends BaseRefundApply<M>> extends Model<M> implements IBean {

	public M setApplyId(java.lang.Integer applyId) {
		set("apply_id", applyId);
		return (M)this;
	}

	public java.lang.Integer getApplyId() {
		return get("apply_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setSellUserId(java.lang.Integer sellUserId) {
		set("sell_user_id", sellUserId);
		return (M)this;
	}

	public java.lang.Integer getSellUserId() {
		return get("sell_user_id");
	}

	public M setApplyType(java.lang.Integer applyType) {
		set("apply_type", applyType);
		return (M)this;
	}

	public java.lang.Integer getApplyType() {
		return get("apply_type");
	}

	public M setApplyReason(java.lang.Integer applyReason) {
		set("apply_reason", applyReason);
		return (M)this;
	}

	public java.lang.Integer getApplyReason() {
		return get("apply_reason");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}

	public java.lang.String getImgUrl() {
		return get("img_url");
	}

	public M setApplyStatus(java.lang.Integer applyStatus) {
		set("apply_status", applyStatus);
		return (M)this;
	}

	public java.lang.Integer getApplyStatus() {
		return get("apply_status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
