package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleComments<M extends BaseArticleComments<M>> extends Model<M> implements IBean {

	public M setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
		return (M)this;
	}

	public java.lang.Integer getCommentId() {
		return get("comment_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setArticleId(java.lang.Integer articleId) {
		set("article_id", articleId);
		return (M)this;
	}

	public java.lang.Integer getArticleId() {
		return get("article_id");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setCommentRank(java.lang.Integer commentRank) {
		set("comment_rank", commentRank);
		return (M)this;
	}

	public java.lang.Integer getCommentRank() {
		return get("comment_rank");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
		return (M)this;
	}

	public java.lang.String getIpAddress() {
		return get("ip_address");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
