package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderDelivery<M extends BaseOrderDelivery<M>> extends Model<M> implements IBean {

	public M setDeliveryId(java.lang.Integer deliveryId) {
		set("delivery_id", deliveryId);
		return (M)this;
	}

	public java.lang.Integer getDeliveryId() {
		return get("delivery_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setCarrierCode(java.lang.String carrierCode) {
		set("carrier_code", carrierCode);
		return (M)this;
	}

	public java.lang.String getCarrierCode() {
		return get("carrier_code");
	}

	public M setCarrierName(java.lang.String carrierName) {
		set("carrier_name", carrierName);
		return (M)this;
	}

	public java.lang.String getCarrierName() {
		return get("carrier_name");
	}

	public M setTrackingNumber(java.lang.String trackingNumber) {
		set("tracking_number", trackingNumber);
		return (M)this;
	}

	public java.lang.String getTrackingNumber() {
		return get("tracking_number");
	}

	public M setDeliveryTime(java.util.Date deliveryTime) {
		set("delivery_time", deliveryTime);
		return (M)this;
	}

	public java.util.Date getDeliveryTime() {
		return get("delivery_time");
	}

	public M setExpressTracking(java.lang.String expressTracking) {
		set("express_tracking", expressTracking);
		return (M)this;
	}

	public java.lang.String getExpressTracking() {
		return get("express_tracking");
	}

	public M setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("last_update_time", lastUpdateTime);
		return (M)this;
	}

	public java.util.Date getLastUpdateTime() {
		return get("last_update_time");
	}

	public M setIsReceipt(java.lang.Boolean isReceipt) {
		set("is_receipt", isReceipt);
		return (M)this;
	}

	public java.lang.Boolean getIsReceipt() {
		return get("is_receipt");
	}

	public M setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
		return (M)this;
	}

	public java.lang.Integer getDeliveryType() {
		return get("delivery_type");
	}

}
