package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderLogs<M extends BaseOrderLogs<M>> extends Model<M> implements IBean {

	public M setLogId(java.lang.Integer logId) {
		set("log_id", logId);
		return (M)this;
	}

	public java.lang.Integer getLogId() {
		return get("log_id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setOperatorType(java.lang.Integer operatorType) {
		set("operator_type", operatorType);
		return (M)this;
	}

	public java.lang.Integer getOperatorType() {
		return get("operator_type");
	}

	public M setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}

	public java.lang.Integer getOperatorId() {
		return get("operator_id");
	}

	public M setLogContent(java.lang.String logContent) {
		set("log_content", logContent);
		return (M)this;
	}

	public java.lang.String getLogContent() {
		return get("log_content");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
