package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProducts<M extends BaseProducts<M>> extends Model<M> implements IBean {

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
		return (M)this;
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

	public M setClassificationId(java.lang.Integer classificationId) {
		set("classification_id", classificationId);
		return (M)this;
	}

	public java.lang.Integer getClassificationId() {
		return get("classification_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public M setProductImg(java.lang.String productImg) {
		set("product_img", productImg);
		return (M)this;
	}

	public java.lang.String getProductImg() {
		return get("product_img");
	}

	public M setProductIntroduction(java.lang.String productIntroduction) {
		set("product_introduction", productIntroduction);
		return (M)this;
	}

	public java.lang.String getProductIntroduction() {
		return get("product_introduction");
	}

	public M setProductPrice(java.lang.String productPrice) {
		set("product_price", productPrice);
		return (M)this;
	}

	public java.lang.String getProductPrice() {
		return get("product_price");
	}

	public M setProductCurrency(java.lang.Integer productCurrency) {
		set("product_currency", productCurrency);
		return (M)this;
	}

	public java.lang.Integer getProductCurrency() {
		return get("product_currency");
	}

	public M setProductCode(java.lang.String productCode) {
		set("product_code", productCode);
		return (M)this;
	}

	public java.lang.String getProductCode() {
		return get("product_code");
	}

	public M setProductMaterial(java.lang.String productMaterial) {
		set("product_material", productMaterial);
		return (M)this;
	}

	public java.lang.String getProductMaterial() {
		return get("product_material");
	}

	public M setProductSize(java.lang.String productSize) {
		set("product_size", productSize);
		return (M)this;
	}

	public java.lang.String getProductSize() {
		return get("product_size");
	}

	public M setProductOrigin(java.lang.String productOrigin) {
		set("product_origin", productOrigin);
		return (M)this;
	}

	public java.lang.String getProductOrigin() {
		return get("product_origin");
	}

	public M setApplicableCrowd(java.lang.String applicableCrowd) {
		set("applicable_crowd", applicableCrowd);
		return (M)this;
	}

	public java.lang.String getApplicableCrowd() {
		return get("applicable_crowd");
	}

	public M setSellStatus(java.lang.Integer sellStatus) {
		set("sell_status", sellStatus);
		return (M)this;
	}

	public java.lang.Integer getSellStatus() {
		return get("sell_status");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setSeries(java.lang.String series) {
		set("series", series);
		return (M)this;
	}

	public java.lang.String getSeries() {
		return get("series");
	}

	public M setSupplyCity(java.lang.String supplyCity) {
		set("supply_city", supplyCity);
		return (M)this;
	}

	public java.lang.String getSupplyCity() {
		return get("supply_city");
	}

	public M setNotice(java.lang.String notice) {
		set("notice", notice);
		return (M)this;
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public M setExtendClassificationId(java.lang.Integer extendClassificationId) {
		set("extend_classification_id", extendClassificationId);
		return (M)this;
	}

	public java.lang.Integer getExtendClassificationId() {
		return get("extend_classification_id");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public M setSystemType(java.lang.Integer systemType) {
		set("system_type", systemType);
		return (M)this;
	}

	public java.lang.Integer getSystemType() {
		return get("system_type");
	}

	public M setProductOriginalPrice(java.lang.String productOriginalPrice) {
		set("product_original_price", productOriginalPrice);
		return (M)this;
	}

	public java.lang.String getProductOriginalPrice() {
		return get("product_original_price");
	}

	public M setIsHidePrice(java.lang.Boolean isHidePrice) {
		set("is_hide_price", isHidePrice);
		return (M)this;
	}

	public java.lang.Boolean getIsHidePrice() {
		return get("is_hide_price");
	}

	public M setIsRecommend(java.lang.Boolean isRecommend) {
		set("is_recommend", isRecommend);
		return (M)this;
	}

	public java.lang.Boolean getIsRecommend() {
		return get("is_recommend");
	}

}
