package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShippingTemplate<M extends BaseShippingTemplate<M>> extends Model<M> implements IBean {

	public M setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
		return (M)this;
	}

	public java.lang.Integer getTemplateId() {
		return get("template_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
		return (M)this;
	}

	public java.lang.String getShippingName() {
		return get("shipping_name");
	}

	public M setShippingInfo(java.lang.String shippingInfo) {
		set("shipping_info", shippingInfo);
		return (M)this;
	}

	public java.lang.String getShippingInfo() {
		return get("shipping_info");
	}

	public M setToChina(java.math.BigDecimal toChina) {
		set("to_china", toChina);
		return (M)this;
	}

	public java.math.BigDecimal getToChina() {
		return get("to_china");
	}

	public M setToForeign(java.math.BigDecimal toForeign) {
		set("to_foreign", toForeign);
		return (M)this;
	}

	public java.math.BigDecimal getToForeign() {
		return get("to_foreign");
	}

	public M setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}

	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
