package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public M setOrderSn(java.lang.Long orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.Long getOrderSn() {
		return get("order_sn");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setSellUserId(java.lang.Integer sellUserId) {
		set("sell_user_id", sellUserId);
		return (M)this;
	}

	public java.lang.Integer getSellUserId() {
		return get("sell_user_id");
	}

	public M setPaymentMethod(java.lang.Integer paymentMethod) {
		set("payment_method", paymentMethod);
		return (M)this;
	}

	public java.lang.Integer getPaymentMethod() {
		return get("payment_method");
	}

	public M setProductAmount(java.math.BigDecimal productAmount) {
		set("product_amount", productAmount);
		return (M)this;
	}

	public java.math.BigDecimal getProductAmount() {
		return get("product_amount");
	}

	public M setShippingFee(java.math.BigDecimal shippingFee) {
		set("shipping_fee", shippingFee);
		return (M)this;
	}

	public java.math.BigDecimal getShippingFee() {
		return get("shipping_fee");
	}

	public M setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
		return (M)this;
	}

	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	public M setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
		return (M)this;
	}

	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public M setPayAmount(java.math.BigDecimal payAmount) {
		set("pay_amount", payAmount);
		return (M)this;
	}

	public java.math.BigDecimal getPayAmount() {
		return get("pay_amount");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
		return (M)this;
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public M setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
		return (M)this;
	}

	public java.lang.Integer getPayStatus() {
		return get("pay_status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public M setPayOrderId(java.lang.String payOrderId) {
		set("pay_order_id", payOrderId);
		return (M)this;
	}

	public java.lang.String getPayOrderId() {
		return get("pay_order_id");
	}

	public M setShippingTime(java.util.Date shippingTime) {
		set("shipping_time", shippingTime);
		return (M)this;
	}

	public java.util.Date getShippingTime() {
		return get("shipping_time");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setConfirmDate(java.util.Date confirmDate) {
		set("confirm_date", confirmDate);
		return (M)this;
	}

	public java.util.Date getConfirmDate() {
		return get("confirm_date");
	}

	public M setIsReceiving(java.lang.Boolean isReceiving) {
		set("is_receiving", isReceiving);
		return (M)this;
	}

	public java.lang.Boolean getIsReceiving() {
		return get("is_receiving");
	}

	public M setVoucherTime(java.util.Date voucherTime) {
		set("voucher_time", voucherTime);
		return (M)this;
	}

	public java.util.Date getVoucherTime() {
		return get("voucher_time");
	}

	public M setIsDelayUpload(java.lang.Boolean isDelayUpload) {
		set("is_delay_upload", isDelayUpload);
		return (M)this;
	}

	public java.lang.Boolean getIsDelayUpload() {
		return get("is_delay_upload");
	}

	public M setIsDelayVoucher(java.lang.Boolean isDelayVoucher) {
		set("is_delay_voucher", isDelayVoucher);
		return (M)this;
	}

	public java.lang.Boolean getIsDelayVoucher() {
		return get("is_delay_voucher");
	}

	public M setVoucherConfirmTime(java.util.Date voucherConfirmTime) {
		set("voucher_confirm_time", voucherConfirmTime);
		return (M)this;
	}

	public java.util.Date getVoucherConfirmTime() {
		return get("voucher_confirm_time");
	}

	public M setAcceptTime(java.util.Date acceptTime) {
		set("accept_time", acceptTime);
		return (M)this;
	}

	public java.util.Date getAcceptTime() {
		return get("accept_time");
	}

	public M setCancelReason(java.lang.Integer cancelReason) {
		set("cancel_reason", cancelReason);
		return (M)this;
	}

	public java.lang.Integer getCancelReason() {
		return get("cancel_reason");
	}

	public M setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
		return (M)this;
	}

	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	public M setReceiptTime(java.util.Date receiptTime) {
		set("receipt_time", receiptTime);
		return (M)this;
	}

	public java.util.Date getReceiptTime() {
		return get("receipt_time");
	}

	public M setSystemType(java.lang.Integer systemType) {
		set("system_type", systemType);
		return (M)this;
	}

	public java.lang.Integer getSystemType() {
		return get("system_type");
	}

}
