package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFriends<M extends BaseFriends<M>> extends Model<M> implements IBean {

	public M setFriendId(java.lang.Integer friendId) {
		set("friend_id", friendId);
		return (M)this;
	}

	public java.lang.Integer getFriendId() {
		return get("friend_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setBuyNickName(java.lang.String buyNickName) {
		set("buy_nick_name", buyNickName);
		return (M)this;
	}

	public java.lang.String getBuyNickName() {
		return get("buy_nick_name");
	}

	public M setSellUserId(java.lang.Integer sellUserId) {
		set("sell_user_id", sellUserId);
		return (M)this;
	}

	public java.lang.Integer getSellUserId() {
		return get("sell_user_id");
	}

	public M setSellNickName(java.lang.String sellNickName) {
		set("sell_nick_name", sellNickName);
		return (M)this;
	}

	public java.lang.String getSellNickName() {
		return get("sell_nick_name");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public M setLasttime(java.util.Date lasttime) {
		set("lasttime", lasttime);
		return (M)this;
	}

	public java.util.Date getLasttime() {
		return get("lasttime");
	}

}
