package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public M setFeedbackId(java.lang.Integer feedbackId) {
		set("feedback_id", feedbackId);
		return (M)this;
	}

	public java.lang.Integer getFeedbackId() {
		return get("feedback_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public M setContactDetails(java.lang.String contactDetails) {
		set("contact_details", contactDetails);
		return (M)this;
	}

	public java.lang.String getContactDetails() {
		return get("contact_details");
	}

	public M setFeedbackTime(java.util.Date feedbackTime) {
		set("feedback_time", feedbackTime);
		return (M)this;
	}

	public java.util.Date getFeedbackTime() {
		return get("feedback_time");
	}

}
